[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$GameDirectory,
    [switch]$Native,
    # Optional three-tone MP3 generated by plugins/NordicRadio/Generate-SeekProbe.py.
    [string]$PlaybackProbeMp3
)
$ErrorActionPreference='Stop'
$repo=Split-Path $PSScriptRoot -Parent
$GameDirectory=(Resolve-Path -LiteralPath $GameDirectory).ProviderPath
if($Native -and (Get-Process -Name valheim,valheim_server -ErrorAction SilentlyContinue)) { throw 'Close Valheim before native tests.' }
if($PlaybackProbeMp3) { $PlaybackProbeMp3=(Resolve-Path -LiteralPath $PlaybackProbeMp3).ProviderPath }
$out=Join-Path $repo ('.cache/mod-audit-'+[guid]::NewGuid().ToString('N').Substring(0,8))
New-Item -ItemType Directory -Force -Path $out | Out-Null
$results=New-Object 'System.Collections.Generic.List[object]'
function Run-Suite([string]$Name,[string]$Script,[string[]]$Arguments=@()) {
    $log=Join-Path $out ($Name+'.log')
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repo $Script) @Arguments *> $log
    $ok=$LASTEXITCODE -eq 0
    $results.Add([pscustomobject]@{name=$Name;passed=$ok;log=$log})
    if($ok) { Write-Output "PASS $Name" }
    else { Write-Output "FAIL $Name"; Get-Content -LiteralPath $log -Tail 8 }
}
Run-Suite 'pack-integrity' 'scripts/Verify.ps1'
Run-Suite 'plugin-dependencies' 'scripts/Audit-Plugins.ps1'
Run-Suite 'anyportal-list' 'plugins/AnyPortalPlus/Tests/Test-List.ps1'
Run-Suite 'anyportal-core' 'plugins/AnyPortalPlus/Tests/Test-Core.ps1'
Run-Suite 'anyportal-map-markers' 'plugins/AnyPortalPlus/Test-Markers.ps1'
Run-Suite 'anyportal-ui' 'plugins/AnyPortalPlus/Test-Ui.ps1'
Run-Suite 'anyportal-package-resources' 'plugins/AnyPortalPlus/Test-PackResources.ps1'
Run-Suite 'inventory-admin-policy' 'plugins/InventoryAdmin/Test-Policy.ps1'
Run-Suite 'inventory-admin-service' 'plugins/InventoryAdmin/Test-Service.ps1'
Run-Suite 'inventory-admin-locations' 'plugins/InventoryAdmin/Test-Locations.ps1'
Run-Suite 'inventory-admin-map' 'plugins/InventoryAdmin/Test-MapOverlay.ps1'
foreach($entry in @('WorldCharacters','ChestSearch','InterfaceInputFix','RenewableResourceTimers','ConfirmMapPinRemoval','NordicRadio','PortalFinder','PlayerSectorSync')) {
    Run-Suite $entry ('plugins/'+$entry+'/Test.ps1') @('-GameDirectory',$GameDirectory)
}
foreach($entry in @('EAQSQuickStackBridge/Test.ps1','ExpeditionLoadouts/Test-Backend.ps1','ExpeditionLoadouts/Test-Presets.ps1','ExpeditionLoadouts/Test-Hotkeys.ps1',
    'ConfirmMapPinRemoval/Test-Presets.ps1','ConfirmMapPinRemoval/Test-PinPresetLocalization.ps1','ConfirmMapPinRemoval/Test-QuickPins.ps1')) {
    Run-Suite ($entry.Replace('/','-').Replace('.ps1','')) ('plugins/'+$entry)
}
Run-Suite 'fermenter-api-build' 'plugins/FermenterCompatibility/Build.ps1' @('-GameDirectory',$GameDirectory,'-OutputFile',(Join-Path $out 'FermenterCompatibility.dll'))
if($Native) {
    # Sequential game processes: separate BepInEx, logs and save directories; no live world is opened.
    Run-Suite 'native-full-pack' 'plugins/ExpeditionLoadouts/Test-Native.ps1' @('-GameDirectory',$GameDirectory)
    Run-Suite 'native-worldcharacters' 'plugins/WorldCharacters/Test-Native.ps1' @('-GameDirectory',$GameDirectory,'-PluginAssembly',(Join-Path $repo 'local-plugins/WorldCharacters.dll'))
    $radioArgs=@('-GameDirectory',$GameDirectory)
    if($PlaybackProbeMp3) { $radioArgs+=@('-TestMp3',$PlaybackProbeMp3,'-CheckPlaybackTransport') }
    Run-Suite 'native-radio' 'plugins/NordicRadio/Test-NativeSmoke.ps1' $radioArgs
}
$results | ConvertTo-Json -Depth 3 | Set-Content -LiteralPath (Join-Path $out 'results.json') -Encoding UTF8
Write-Output "Audit logs: $out"
if(@($results | Where-Object { -not $_.passed }).Count) { throw 'Mod audit has failed suites; see their logs.' }
Write-Output 'Available checks passed. This does not certify live multiplayer behavior or every vendor code path.'
